---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-cloudwatch-metrics
  namespace: flux-system
spec:
  releaseName: aws-cloudwatch-metrics
  targetNamespace: aws-system
  storageNamespace: aws-system
  interval: 10m0s
  chart:
    spec:
      chart: aws-cloudwatch-metrics
      version: 0.0.5
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  values:
    clusterName: sandbox
    serviceAccount:
      create: false
      name: aws-cloudwatch-agent
  install: {}